// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface ILocation {
    location: Location[];
}

export interface Location {
    id:           number;
    name:         string;
    /* iso3:         string;
    iso2:         string;
    country_code: string;
    phone_code:   string;
    capital:      string;
    currency:     string; */
    states:       { [key: string]: string[] };
}
